### ISSUE TITLE
Add options to load different projects

### ISSUE THREAD

**Issue by not-an-aardvark** [not-an-aardvark/eslint-canary#1]
* `--project-file-path=foo.yml`: Load projects from a file other than `projects.yml`
* `--project=foo --project=bar`: Only lint the `foo` and `bar` projects from the `projects.yml` file
* `--skip=foo` Lint the projects in `projects.yml`, but skip the `foo` project

**Comment by nzakas** [comment]
We've decided to archive this repository as it's no longer in use.
