### ISSUE TITLE
Suggestion: Create a utility that will attempt to run eslint-canary on latest master for projects and update hardcoded commit in projects.yml

### ISSUE THREAD

**Issue by platinumazure** [not-an-aardvark/eslint-canary#11]
In order to keep eslint-canary relevant and useful, it would be best to run it against latest version of repositories where possible (or as close to it as possible).

To make maintenance easier, I wanted to suggest creating a utility which will do the following:

* For each repository in projects.yml:
    1. Run eslint-canary against currently configured commit
    1. Try to checkout master (or default GH branch) and run eslint-canary against it
    1. If eslint-canary passes on both runs, update projects.yml to use the hash of the commit pointed to by the master branch

As a later enhancement, this utility could also document failures against the master branch and document them somewhere for us, so we can decide if we need to change the CLI arguments or contact the developers (or do nothing).

cc @not-an-aardvark

**Comment by nzakas** [comment]
We've decided to archive this repository as it's no longer in use.
